#!/bin/sh

# Copyright © 2015 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
#
# Created: 2015-03-01
# Last changed: 2015-03-01 22:17:28
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.
#
## Prepare wpa_supplicant environment for initrd.
#
# Wireless configuration is in /etc/initramfs-tools/etc/wpa_supplicant.conf


. /usr/share/initramfs-tools/hook-functions
. "$CONFDIR/initramfs.conf"

#manual_add_modules iwlmvm
copy_modules_dir kernel/drivers/net/wireless
copy_exec /sbin/wpa_supplicant

if ! test -e "$CONFDIR/etc/wpa_supplicant.conf"; then
    echo "WARNING $CONFDIR/etc/wpa_supplicant.conf not found. Wireless network might not be usable."
fi

cp "$CONFDIR/etc/wpa_supplicant.conf" $DESTDIR/etc/
