#!/bin/sh

# Copyright © 2015 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

# Created: 2015-03-01
# Last changed: 2015-03-01 22:10:43

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


## Bring wireless interface up at boot time.
#
# A wireless interface is defined in 'wlan' variable as given as an initrd
# parameter such as:
#      wlan=wlan0
#
# If no 'wlan' variable is defined, try all 'wlan*' interface found on the
# system.
#
# If wlan is 'none' or 'off', or 'false', do not use wlan at boot time.
#


PREREQ="udev"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions

if test -n "$wlan"; then
    case $wlan in
	none|off|false) exit 0;;
    esac
    DEVICE=$wlan
else
    for iface in $(ifconfig -a | awk '{if($1~/^wlan/&&$2=="Link"&&$3=="encap:Ethernet"){print $1}}'); do
	DEVICE=$iface
	break
    done
fi

if test -n "$DEVICE"; then
    if test -d /sys/class/net/$DEVICE; then
	log_begin_msg "Bringing wireless $DEVICE up"
	log_end_msg
	wpa_supplicant -B -i$DEVICE \
		       -c /etc/wpa_supplicant.conf \
		       -P /var/run/wpa_supplicant.pid
	configure_networking
    fi
fi
