#!/bin/sh

# Copyright © 2015 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
#
# Created: 2015-03-01
# Last changed: 2015-03-01 22:13:15
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

## Stop wpa_supplicant daemon before leaving initrd to allow real system
## wpa_supplicant to take over.

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /scripts/functions

[ -r /var/run/wpa_supplicant.pid ] || exit 0

log_begin_msg "Stopping wpa_supplicant"

kill `cat /var/run/wpa_supplicant.pid`

log_end_msg
